//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOLITE_ClientExample.LEIServiceReference {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/soap/envelope/")]
    public partial class Fault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlQualifiedName faultcodeField;
        
        private string faultstringField;
        
        private string faultactorField;
        
        private detail detailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.Xml.XmlQualifiedName faultcode {
            get {
                return this.faultcodeField;
            }
            set {
                this.faultcodeField = value;
                this.RaisePropertyChanged("faultcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string faultstring {
            get {
                return this.faultstringField;
            }
            set {
                this.faultstringField = value;
                this.RaisePropertyChanged("faultstring");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI", Order=2)]
        public string faultactor {
            get {
                return this.faultactorField;
            }
            set {
                this.faultactorField = value;
                this.RaisePropertyChanged("faultactor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public detail detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
                this.RaisePropertyChanged("detail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/soap/envelope/")]
    public partial class detail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class LEIRecordNextVersionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016", Order=0)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class RegistrationNextVersionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016", Order=0)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class ValidationAuthorityType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string validationAuthorityIDField;
        
        private string otherValidationAuthorityIDField;
        
        private string validationAuthorityEntityIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ValidationAuthorityID {
            get {
                return this.validationAuthorityIDField;
            }
            set {
                this.validationAuthorityIDField = value;
                this.RaisePropertyChanged("ValidationAuthorityID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string OtherValidationAuthorityID {
            get {
                return this.otherValidationAuthorityIDField;
            }
            set {
                this.otherValidationAuthorityIDField = value;
                this.RaisePropertyChanged("OtherValidationAuthorityID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ValidationAuthorityEntityID {
            get {
                return this.validationAuthorityEntityIDField;
            }
            set {
                this.validationAuthorityEntityIDField = value;
                this.RaisePropertyChanged("ValidationAuthorityEntityID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class RegistrationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime initialRegistrationDateField;
        
        private System.DateTime lastUpdateDateField;
        
        private RegistrationStatusEnum registrationStatusField;
        
        private System.DateTime nextRenewalDateField;
        
        private string managingLOUField;
        
        private ValidationSourcesEnum validationSourcesField;
        
        private bool validationSourcesFieldSpecified;
        
        private ValidationAuthorityType validationAuthorityField;
        
        private ValidationAuthorityType[] otherValidationAuthoritiesField;
        
        private RegistrationNextVersionType nextVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime InitialRegistrationDate {
            get {
                return this.initialRegistrationDateField;
            }
            set {
                this.initialRegistrationDateField = value;
                this.RaisePropertyChanged("InitialRegistrationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime LastUpdateDate {
            get {
                return this.lastUpdateDateField;
            }
            set {
                this.lastUpdateDateField = value;
                this.RaisePropertyChanged("LastUpdateDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public RegistrationStatusEnum RegistrationStatus {
            get {
                return this.registrationStatusField;
            }
            set {
                this.registrationStatusField = value;
                this.RaisePropertyChanged("RegistrationStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime NextRenewalDate {
            get {
                return this.nextRenewalDateField;
            }
            set {
                this.nextRenewalDateField = value;
                this.RaisePropertyChanged("NextRenewalDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ManagingLOU {
            get {
                return this.managingLOUField;
            }
            set {
                this.managingLOUField = value;
                this.RaisePropertyChanged("ManagingLOU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public ValidationSourcesEnum ValidationSources {
            get {
                return this.validationSourcesField;
            }
            set {
                this.validationSourcesField = value;
                this.RaisePropertyChanged("ValidationSources");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValidationSourcesSpecified {
            get {
                return this.validationSourcesFieldSpecified;
            }
            set {
                this.validationSourcesFieldSpecified = value;
                this.RaisePropertyChanged("ValidationSourcesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public ValidationAuthorityType ValidationAuthority {
            get {
                return this.validationAuthorityField;
            }
            set {
                this.validationAuthorityField = value;
                this.RaisePropertyChanged("ValidationAuthority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("OtherValidationAuthority", IsNullable=false)]
        public ValidationAuthorityType[] OtherValidationAuthorities {
            get {
                return this.otherValidationAuthoritiesField;
            }
            set {
                this.otherValidationAuthoritiesField = value;
                this.RaisePropertyChanged("OtherValidationAuthorities");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public RegistrationNextVersionType NextVersion {
            get {
                return this.nextVersionField;
            }
            set {
                this.nextVersionField = value;
                this.RaisePropertyChanged("NextVersion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public enum RegistrationStatusEnum {
        
        /// <remarks/>
        PENDING_VALIDATION,
        
        /// <remarks/>
        ISSUED,
        
        /// <remarks/>
        DUPLICATE,
        
        /// <remarks/>
        LAPSED,
        
        /// <remarks/>
        MERGED,
        
        /// <remarks/>
        RETIRED,
        
        /// <remarks/>
        ANNULLED,
        
        /// <remarks/>
        CANCELLED,
        
        /// <remarks/>
        TRANSFERRED,
        
        /// <remarks/>
        PENDING_TRANSFER,
        
        /// <remarks/>
        PENDING_ARCHIVAL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public enum ValidationSourcesEnum {
        
        /// <remarks/>
        PENDING,
        
        /// <remarks/>
        ENTITY_SUPPLIED_ONLY,
        
        /// <remarks/>
        PARTIALLY_CORROBORATED,
        
        /// <remarks/>
        FULLY_CORROBORATED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class EntityNextVersionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016", Order=0)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class SuccessorEntityType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SuccessorEntityName", typeof(NameType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SuccessorLEI", typeof(string), Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OtherEntityNameType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class NameType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string langField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
                this.RaisePropertyChanged("lang");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class OtherEntityNameType : NameType {
        
        private EntityNameTypeEnum typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public EntityNameTypeEnum type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public enum EntityNameTypeEnum {
        
        /// <remarks/>
        ALTERNATIVE_LANGUAGE_LEGAL_NAME,
        
        /// <remarks/>
        PREVIOUS_LEGAL_NAME,
        
        /// <remarks/>
        TRADING_OR_OPERATING_NAME,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class AssociatedEntityType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object itemField;
        
        private AssociatedEntityTypeEnum typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AssociatedEntityName", typeof(NameType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("AssociatedLEI", typeof(string), Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AssociatedEntityTypeEnum type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public enum AssociatedEntityTypeEnum {
        
        /// <remarks/>
        FUND_FAMILY,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class LegalFormType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string entityLegalFormCodeField;
        
        private string otherLegalFormField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EntityLegalFormCode {
            get {
                return this.entityLegalFormCodeField;
            }
            set {
                this.entityLegalFormCodeField = value;
                this.RaisePropertyChanged("EntityLegalFormCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string OtherLegalForm {
            get {
                return this.otherLegalFormField;
            }
            set {
                this.otherLegalFormField = value;
                this.RaisePropertyChanged("OtherLegalForm");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class RegistrationAuthorityType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string registrationAuthorityIDField;
        
        private string otherRegistrationAuthorityIDField;
        
        private string registrationAuthorityEntityIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RegistrationAuthorityID {
            get {
                return this.registrationAuthorityIDField;
            }
            set {
                this.registrationAuthorityIDField = value;
                this.RaisePropertyChanged("RegistrationAuthorityID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string OtherRegistrationAuthorityID {
            get {
                return this.otherRegistrationAuthorityIDField;
            }
            set {
                this.otherRegistrationAuthorityIDField = value;
                this.RaisePropertyChanged("OtherRegistrationAuthorityID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RegistrationAuthorityEntityID {
            get {
                return this.registrationAuthorityEntityIDField;
            }
            set {
                this.registrationAuthorityEntityIDField = value;
                this.RaisePropertyChanged("RegistrationAuthorityEntityID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransliteratedOtherAddressType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class TransliteratedAddressType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string firstAddressLineField;
        
        private string addressNumberField;
        
        private string addressNumberWithinBuildingField;
        
        private string mailRoutingField;
        
        private string[] additionalAddressLineField;
        
        private string cityField;
        
        private string regionField;
        
        private string countryField;
        
        private string postalCodeField;
        
        private string langField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FirstAddressLine {
            get {
                return this.firstAddressLineField;
            }
            set {
                this.firstAddressLineField = value;
                this.RaisePropertyChanged("FirstAddressLine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AddressNumber {
            get {
                return this.addressNumberField;
            }
            set {
                this.addressNumberField = value;
                this.RaisePropertyChanged("AddressNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AddressNumberWithinBuilding {
            get {
                return this.addressNumberWithinBuildingField;
            }
            set {
                this.addressNumberWithinBuildingField = value;
                this.RaisePropertyChanged("AddressNumberWithinBuilding");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MailRouting {
            get {
                return this.mailRoutingField;
            }
            set {
                this.mailRoutingField = value;
                this.RaisePropertyChanged("MailRouting");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdditionalAddressLine", Order=4)]
        public string[] AdditionalAddressLine {
            get {
                return this.additionalAddressLineField;
            }
            set {
                this.additionalAddressLineField = value;
                this.RaisePropertyChanged("AdditionalAddressLine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("Region");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("PostalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
                this.RaisePropertyChanged("lang");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class TransliteratedOtherAddressType : TransliteratedAddressType {
        
        private TransliteratedAddressTypeEnum typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TransliteratedAddressTypeEnum type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public enum TransliteratedAddressTypeEnum {
        
        /// <remarks/>
        AUTO_ASCII_TRANSLITERATED_LEGAL_ADDRESS,
        
        /// <remarks/>
        AUTO_ASCII_TRANSLITERATED_HEADQUARTERS_ADDRESS,
        
        /// <remarks/>
        PREFERRED_ASCII_TRANSLITERATED_LEGAL_ADDRESS,
        
        /// <remarks/>
        PREFERRED_ASCII_TRANSLITERATED_HEADQUARTERS_ADDRESS,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OtherAddressType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class AddressType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string firstAddressLineField;
        
        private string addressNumberField;
        
        private string addressNumberWithinBuildingField;
        
        private string mailRoutingField;
        
        private string[] additionalAddressLineField;
        
        private string cityField;
        
        private string regionField;
        
        private string countryField;
        
        private string postalCodeField;
        
        private string langField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FirstAddressLine {
            get {
                return this.firstAddressLineField;
            }
            set {
                this.firstAddressLineField = value;
                this.RaisePropertyChanged("FirstAddressLine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AddressNumber {
            get {
                return this.addressNumberField;
            }
            set {
                this.addressNumberField = value;
                this.RaisePropertyChanged("AddressNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AddressNumberWithinBuilding {
            get {
                return this.addressNumberWithinBuildingField;
            }
            set {
                this.addressNumberWithinBuildingField = value;
                this.RaisePropertyChanged("AddressNumberWithinBuilding");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MailRouting {
            get {
                return this.mailRoutingField;
            }
            set {
                this.mailRoutingField = value;
                this.RaisePropertyChanged("MailRouting");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdditionalAddressLine", Order=4)]
        public string[] AdditionalAddressLine {
            get {
                return this.additionalAddressLineField;
            }
            set {
                this.additionalAddressLineField = value;
                this.RaisePropertyChanged("AdditionalAddressLine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("Region");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("PostalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
                this.RaisePropertyChanged("lang");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class OtherAddressType : AddressType {
        
        private AddressTypeEnum typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AddressTypeEnum type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public enum AddressTypeEnum {
        
        /// <remarks/>
        ALTERNATIVE_LANGUAGE_LEGAL_ADDRESS,
        
        /// <remarks/>
        ALTERNATIVE_LANGUAGE_HEADQUARTERS_ADDRESS,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransliteratedOtherEntityNameType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class TransliteratedNameType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string langField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
                this.RaisePropertyChanged("lang");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class TransliteratedOtherEntityNameType : TransliteratedNameType {
        
        private TransliteratedEntityNameTypeEnum typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TransliteratedEntityNameTypeEnum type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public enum TransliteratedEntityNameTypeEnum {
        
        /// <remarks/>
        PREFERRED_ASCII_TRANSLITERATED_LEGAL_NAME,
        
        /// <remarks/>
        AUTO_ASCII_TRANSLITERATED_LEGAL_NAME,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class EntityType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private NameType legalNameField;
        
        private OtherEntityNameType[] otherEntityNamesField;
        
        private TransliteratedOtherEntityNameType[] transliteratedOtherEntityNamesField;
        
        private AddressType legalAddressField;
        
        private AddressType headquartersAddressField;
        
        private OtherAddressType[] otherAddressesField;
        
        private TransliteratedOtherAddressType[] transliteratedOtherAddressesField;
        
        private RegistrationAuthorityType registrationAuthorityField;
        
        private string legalJurisdictionField;
        
        private EntityCategoryTypeEnum entityCategoryField;
        
        private bool entityCategoryFieldSpecified;
        
        private LegalFormType legalFormField;
        
        private AssociatedEntityType associatedEntityField;
        
        private EntityStatusEnum entityStatusField;
        
        private System.DateTime entityExpirationDateField;
        
        private bool entityExpirationDateFieldSpecified;
        
        private EntityExpirationReasonEnum entityExpirationReasonField;
        
        private bool entityExpirationReasonFieldSpecified;
        
        private SuccessorEntityType successorEntityField;
        
        private EntityNextVersionType nextVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public NameType LegalName {
            get {
                return this.legalNameField;
            }
            set {
                this.legalNameField = value;
                this.RaisePropertyChanged("LegalName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("OtherEntityName", IsNullable=false)]
        public OtherEntityNameType[] OtherEntityNames {
            get {
                return this.otherEntityNamesField;
            }
            set {
                this.otherEntityNamesField = value;
                this.RaisePropertyChanged("OtherEntityNames");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("TransliteratedOtherEntityName", IsNullable=false)]
        public TransliteratedOtherEntityNameType[] TransliteratedOtherEntityNames {
            get {
                return this.transliteratedOtherEntityNamesField;
            }
            set {
                this.transliteratedOtherEntityNamesField = value;
                this.RaisePropertyChanged("TransliteratedOtherEntityNames");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public AddressType LegalAddress {
            get {
                return this.legalAddressField;
            }
            set {
                this.legalAddressField = value;
                this.RaisePropertyChanged("LegalAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public AddressType HeadquartersAddress {
            get {
                return this.headquartersAddressField;
            }
            set {
                this.headquartersAddressField = value;
                this.RaisePropertyChanged("HeadquartersAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("OtherAddress", IsNullable=false)]
        public OtherAddressType[] OtherAddresses {
            get {
                return this.otherAddressesField;
            }
            set {
                this.otherAddressesField = value;
                this.RaisePropertyChanged("OtherAddresses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("TransliteratedOtherAddress", IsNullable=false)]
        public TransliteratedOtherAddressType[] TransliteratedOtherAddresses {
            get {
                return this.transliteratedOtherAddressesField;
            }
            set {
                this.transliteratedOtherAddressesField = value;
                this.RaisePropertyChanged("TransliteratedOtherAddresses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public RegistrationAuthorityType RegistrationAuthority {
            get {
                return this.registrationAuthorityField;
            }
            set {
                this.registrationAuthorityField = value;
                this.RaisePropertyChanged("RegistrationAuthority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string LegalJurisdiction {
            get {
                return this.legalJurisdictionField;
            }
            set {
                this.legalJurisdictionField = value;
                this.RaisePropertyChanged("LegalJurisdiction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public EntityCategoryTypeEnum EntityCategory {
            get {
                return this.entityCategoryField;
            }
            set {
                this.entityCategoryField = value;
                this.RaisePropertyChanged("EntityCategory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EntityCategorySpecified {
            get {
                return this.entityCategoryFieldSpecified;
            }
            set {
                this.entityCategoryFieldSpecified = value;
                this.RaisePropertyChanged("EntityCategorySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public LegalFormType LegalForm {
            get {
                return this.legalFormField;
            }
            set {
                this.legalFormField = value;
                this.RaisePropertyChanged("LegalForm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public AssociatedEntityType AssociatedEntity {
            get {
                return this.associatedEntityField;
            }
            set {
                this.associatedEntityField = value;
                this.RaisePropertyChanged("AssociatedEntity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public EntityStatusEnum EntityStatus {
            get {
                return this.entityStatusField;
            }
            set {
                this.entityStatusField = value;
                this.RaisePropertyChanged("EntityStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public System.DateTime EntityExpirationDate {
            get {
                return this.entityExpirationDateField;
            }
            set {
                this.entityExpirationDateField = value;
                this.RaisePropertyChanged("EntityExpirationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EntityExpirationDateSpecified {
            get {
                return this.entityExpirationDateFieldSpecified;
            }
            set {
                this.entityExpirationDateFieldSpecified = value;
                this.RaisePropertyChanged("EntityExpirationDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public EntityExpirationReasonEnum EntityExpirationReason {
            get {
                return this.entityExpirationReasonField;
            }
            set {
                this.entityExpirationReasonField = value;
                this.RaisePropertyChanged("EntityExpirationReason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EntityExpirationReasonSpecified {
            get {
                return this.entityExpirationReasonFieldSpecified;
            }
            set {
                this.entityExpirationReasonFieldSpecified = value;
                this.RaisePropertyChanged("EntityExpirationReasonSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public SuccessorEntityType SuccessorEntity {
            get {
                return this.successorEntityField;
            }
            set {
                this.successorEntityField = value;
                this.RaisePropertyChanged("SuccessorEntity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public EntityNextVersionType NextVersion {
            get {
                return this.nextVersionField;
            }
            set {
                this.nextVersionField = value;
                this.RaisePropertyChanged("NextVersion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public enum EntityCategoryTypeEnum {
        
        /// <remarks/>
        BRANCH,
        
        /// <remarks/>
        FUND,
        
        /// <remarks/>
        SOLE_PROPRIETOR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public enum EntityStatusEnum {
        
        /// <remarks/>
        ACTIVE,
        
        /// <remarks/>
        INACTIVE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public enum EntityExpirationReasonEnum {
        
        /// <remarks/>
        DISSOLVED,
        
        /// <remarks/>
        CORPORATE_ACTION,
        
        /// <remarks/>
        OTHER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class LEIRecordType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string lEIField;
        
        private EntityType entityField;
        
        private RegistrationType registrationField;
        
        private LEIRecordNextVersionType nextVersionField;
        
        private ExtensionType extensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string LEI {
            get {
                return this.lEIField;
            }
            set {
                this.lEIField = value;
                this.RaisePropertyChanged("LEI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public EntityType Entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
                this.RaisePropertyChanged("Entity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public RegistrationType Registration {
            get {
                return this.registrationField;
            }
            set {
                this.registrationField = value;
                this.RaisePropertyChanged("Registration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public LEIRecordNextVersionType NextVersion {
            get {
                return this.nextVersionField;
            }
            set {
                this.nextVersionField = value;
                this.RaisePropertyChanged("NextVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public ExtensionType Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
                this.RaisePropertyChanged("Extension");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class ExtensionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class LEIRecordsType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LEIRecordType[] lEIRecordField;
        
        private ExtensionType extensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LEIRecord", Order=0)]
        public LEIRecordType[] LEIRecord {
            get {
                return this.lEIRecordField;
            }
            set {
                this.lEIRecordField = value;
                this.RaisePropertyChanged("LEIRecord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ExtensionType Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
                this.RaisePropertyChanged("Extension");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class HeaderNextVersionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016", Order=0)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class LEIHeaderType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime contentDateField;
        
        private string originatorField;
        
        private FileContentEnum fileContentField;
        
        private System.DateTime deltaStartField;
        
        private bool deltaStartFieldSpecified;
        
        private string recordCountField;
        
        private HeaderNextVersionType nextVersionField;
        
        private ExtensionType extensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime ContentDate {
            get {
                return this.contentDateField;
            }
            set {
                this.contentDateField = value;
                this.RaisePropertyChanged("ContentDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Originator {
            get {
                return this.originatorField;
            }
            set {
                this.originatorField = value;
                this.RaisePropertyChanged("Originator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public FileContentEnum FileContent {
            get {
                return this.fileContentField;
            }
            set {
                this.fileContentField = value;
                this.RaisePropertyChanged("FileContent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime DeltaStart {
            get {
                return this.deltaStartField;
            }
            set {
                this.deltaStartField = value;
                this.RaisePropertyChanged("DeltaStart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeltaStartSpecified {
            get {
                return this.deltaStartFieldSpecified;
            }
            set {
                this.deltaStartFieldSpecified = value;
                this.RaisePropertyChanged("DeltaStartSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=4)]
        public string RecordCount {
            get {
                return this.recordCountField;
            }
            set {
                this.recordCountField = value;
                this.RaisePropertyChanged("RecordCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public HeaderNextVersionType NextVersion {
            get {
                return this.nextVersionField;
            }
            set {
                this.nextVersionField = value;
                this.RaisePropertyChanged("NextVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public ExtensionType Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
                this.RaisePropertyChanged("Extension");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public enum FileContentEnum {
        
        /// <remarks/>
        LOU_FULL_PUBLISHED,
        
        /// <remarks/>
        LOU_DELTA_PUBLISHED,
        
        /// <remarks/>
        GLEIF_FULL_PUBLISHED,
        
        /// <remarks/>
        GLEIF_DELTA_PUBLISHED,
        
        /// <remarks/>
        QUERY_RESPONSE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class LEIData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LEIHeaderType lEIHeaderField;
        
        private LEIRecordsType lEIRecordsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public LEIHeaderType LEIHeader {
            get {
                return this.lEIHeaderField;
            }
            set {
                this.lEIHeaderField = value;
                this.RaisePropertyChanged("LEIHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public LEIRecordsType LEIRecords {
            get {
                return this.lEIRecordsField;
            }
            set {
                this.lEIRecordsField = value;
                this.RaisePropertyChanged("LEIRecords");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class GetLeiCodeInfoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LEIData lEIDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public LEIData LEIData {
            get {
                return this.lEIDataField;
            }
            set {
                this.lEIDataField = value;
                this.RaisePropertyChanged("LEIData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class GetLeiCodeInfoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cmp_name", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("lei", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("reg_num", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
                this.RaisePropertyChanged("ItemElementName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2114.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        cmp_name,
        
        /// <remarks/>
        lei,
        
        /// <remarks/>
        reg_num,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://oracle.com/sca/soapservice/Tests/ClientProxyService/ClientProxyService", ConfigurationName="LEIServiceReference.getLeiCodeInfo_ptt")]
    public interface getLeiCodeInfo_ptt {
        
        // CODEGEN: Generating message contract since the operation getLeiCodeInfo is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="getLeiCodeInfo", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(IOLITE_ClientExample.LEIServiceReference.Fault), Action="getLeiCodeInfo", Name="Fault", Namespace="http://schemas.xmlsoap.org/soap/envelope/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TransliteratedAddressType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TransliteratedNameType))]
        IOLITE_ClientExample.LEIServiceReference.getLeiCodeInfoResponse1 getLeiCodeInfo(IOLITE_ClientExample.LEIServiceReference.getLeiCodeInfoRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getLeiCodeInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<IOLITE_ClientExample.LEIServiceReference.getLeiCodeInfoResponse1> getLeiCodeInfoAsync(IOLITE_ClientExample.LEIServiceReference.getLeiCodeInfoRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLeiCodeInfoRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016", Order=0)]
        public IOLITE_ClientExample.LEIServiceReference.GetLeiCodeInfoRequest getLeiCodeInfoRequest;
        
        public getLeiCodeInfoRequest1() {
        }
        
        public getLeiCodeInfoRequest1(IOLITE_ClientExample.LEIServiceReference.GetLeiCodeInfoRequest getLeiCodeInfoRequest) {
            this.getLeiCodeInfoRequest = getLeiCodeInfoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLeiCodeInfoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016", Order=0)]
        public IOLITE_ClientExample.LEIServiceReference.GetLeiCodeInfoResponse getLeiCodeInfoResponse;
        
        public getLeiCodeInfoResponse1() {
        }
        
        public getLeiCodeInfoResponse1(IOLITE_ClientExample.LEIServiceReference.GetLeiCodeInfoResponse getLeiCodeInfoResponse) {
            this.getLeiCodeInfoResponse = getLeiCodeInfoResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface getLeiCodeInfo_pttChannel : IOLITE_ClientExample.LEIServiceReference.getLeiCodeInfo_ptt, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getLeiCodeInfo_pttClient : System.ServiceModel.ClientBase<IOLITE_ClientExample.LEIServiceReference.getLeiCodeInfo_ptt>, IOLITE_ClientExample.LEIServiceReference.getLeiCodeInfo_ptt {
        
        public getLeiCodeInfo_pttClient() {
        }
        
        public getLeiCodeInfo_pttClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public getLeiCodeInfo_pttClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public getLeiCodeInfo_pttClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public getLeiCodeInfo_pttClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IOLITE_ClientExample.LEIServiceReference.getLeiCodeInfoResponse1 IOLITE_ClientExample.LEIServiceReference.getLeiCodeInfo_ptt.getLeiCodeInfo(IOLITE_ClientExample.LEIServiceReference.getLeiCodeInfoRequest1 request) {
            return base.Channel.getLeiCodeInfo(request);
        }
        
        public IOLITE_ClientExample.LEIServiceReference.GetLeiCodeInfoResponse getLeiCodeInfo(IOLITE_ClientExample.LEIServiceReference.GetLeiCodeInfoRequest getLeiCodeInfoRequest) {
            IOLITE_ClientExample.LEIServiceReference.getLeiCodeInfoRequest1 inValue = new IOLITE_ClientExample.LEIServiceReference.getLeiCodeInfoRequest1();
            inValue.getLeiCodeInfoRequest = getLeiCodeInfoRequest;
            IOLITE_ClientExample.LEIServiceReference.getLeiCodeInfoResponse1 retVal = ((IOLITE_ClientExample.LEIServiceReference.getLeiCodeInfo_ptt)(this)).getLeiCodeInfo(inValue);
            return retVal.getLeiCodeInfoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IOLITE_ClientExample.LEIServiceReference.getLeiCodeInfoResponse1> IOLITE_ClientExample.LEIServiceReference.getLeiCodeInfo_ptt.getLeiCodeInfoAsync(IOLITE_ClientExample.LEIServiceReference.getLeiCodeInfoRequest1 request) {
            return base.Channel.getLeiCodeInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<IOLITE_ClientExample.LEIServiceReference.getLeiCodeInfoResponse1> getLeiCodeInfoAsync(IOLITE_ClientExample.LEIServiceReference.GetLeiCodeInfoRequest getLeiCodeInfoRequest) {
            IOLITE_ClientExample.LEIServiceReference.getLeiCodeInfoRequest1 inValue = new IOLITE_ClientExample.LEIServiceReference.getLeiCodeInfoRequest1();
            inValue.getLeiCodeInfoRequest = getLeiCodeInfoRequest;
            return ((IOLITE_ClientExample.LEIServiceReference.getLeiCodeInfo_ptt)(this)).getLeiCodeInfoAsync(inValue);
        }
    }
}
